from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
import json
import os
import re

from engine.auth import require_admin
from engine.db import get_db

router = APIRouter(prefix="/api/admin/stories", tags=["admin_stories"])

def load_prd():
    """Load the PRD JSON file."""
    prd_path = "prd.json"
    if not os.path.exists(prd_path):
        return {}
    try:
        with open(prd_path, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return {}

def generate_test_stub(story: dict) -> str:
    """Generate a Python test file skeleton based on story acceptance criteria."""
    story_id = story.get("id", "0")
    title = story.get("title", "Untitled Story")
    test_file_path = story.get("test_file", f"tests/test_story_{story_id}.py")
    
    # Extract acceptance criteria
    description = story.get("description", "")
    acceptance = story.get("acceptance", "")
    
    # Parse acceptance criteria into individual test cases
    # Assuming acceptance is a string like "Test: X. Test: Y. Test: Z."
    # or a list. The prompt says "Reads story from prd.json".
    # We'll handle string format commonly used in these stories.
    
    test_cases = []
    if isinstance(acceptance, str):
        # Split by "Test: " and clean up
        parts = re.split(r'Test:\s*', acceptance)
        for part in parts:
            part = part.strip()
            if part:
                # Remove trailing periods or extra text if needed
                test_cases.append(part)
    elif isinstance(acceptance, list):
        for item in acceptance:
            if isinstance(item, str):
                test_cases.append(item)
    
    # Generate Python code
    lines = [
        '"""Test file generated by Story 174."""',
        '',
        'def test_s174_generated_stub():',
        f'    """Story {story_id}: {title}."""',
        '    # TODO: Implement test logic based on acceptance criteria',
        '    pass',
        ''
    ]
    
    # If we have specific acceptance criteria, create specific stubs
    if test_cases:
        lines = [
            '"""Test file generated by Story 174."""',
            '',
        ]
        for i, case in enumerate(test_cases):
            # Create a safe function name from the case description
            func_name = f"test_s174_{story_id}_case_{i+1}"
            # Sanitize description for docstring
            clean_case = case.replace('"', "'").replace("\n", " ")
            lines.extend([
                f'def {func_name}():',
                f'    """Story {story_id}: {clean_case}."""',
                '    # TODO: Implement test logic',
                '    pass',
                ''
            ])
    
    return "\n".join(lines)

@router.post("/stories/{story_id}/generate-test", status_code=201)
def generate_test_file(
    story_id: int,
    db: Session = Depends(get_db),
    _admin: str = Depends(require_admin)
):
    """
    Generate a skeleton test file for a given story ID.
    Reads from prd.json and writes to the specified test_file path.
    """
    prd = load_prd()
    
    # Find the story in the PRD
    story = None
    for s in prd.get("stories", []):
        if s.get("id") == story_id:
            story = s
            break
    
    if not story:
        raise HTTPException(status_code=404, detail="Story not found in prd.json")
    
    test_file_path = story.get("test_file")
    if not test_file_path:
        raise HTTPException(status_code=422, detail="Story missing 'test_file' attribute")
    
    # Generate content
    content = generate_test_stub(story)
    
    # Ensure directory exists
    directory = os.path.dirname(test_file_path)
    if directory and not os.path.exists(directory):
        os.makedirs(directory, exist_ok=True)
    
    # Write file
    try:
        with open(test_file_path, "w") as f:
            f.write(content)
    except IOError as e:
        raise HTTPException(status_code=500, detail=f"Failed to write test file: {str(e)}")
    
    return {
        "status": "success",
        "story_id": story_id,
        "test_file": test_file_path,
        "message": "Test file generated successfully"
    }