# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qtown import academy_pb2 as qtown_dot_academy__pb2
from qtown import common_pb2 as qtown_dot_common__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in qtown/academy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcademyStub(object):
    """─── Academy Service (Python + LangChain/LangGraph + Ollama) ───
    AI/ML neighborhood. NPC decision agents, multi-model routing,
    RAG over town history via pgvector.
    Proves: LangGraph state machines, Ollama local inference, RAG source attribution.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/qtown.Academy/Health',
                request_serializer=qtown_dot_common__pb2.HealthRequest.SerializeToString,
                response_deserializer=qtown_dot_common__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.NPCDecide = channel.unary_unary(
                '/qtown.Academy/NPCDecide',
                request_serializer=qtown_dot_academy__pb2.NPCDecideRequest.SerializeToString,
                response_deserializer=qtown_dot_academy__pb2.NPCDecideResponse.FromString,
                _registered_method=True)
        self.GenerateDialogue = channel.unary_unary(
                '/qtown.Academy/GenerateDialogue',
                request_serializer=qtown_dot_academy__pb2.DialogueRequest.SerializeToString,
                response_deserializer=qtown_dot_academy__pb2.DialogueResponse.FromString,
                _registered_method=True)
        self.GenerateNewspaper = channel.unary_unary(
                '/qtown.Academy/GenerateNewspaper',
                request_serializer=qtown_dot_academy__pb2.NewspaperRequest.SerializeToString,
                response_deserializer=qtown_dot_academy__pb2.NewspaperResponse.FromString,
                _registered_method=True)
        self.SearchHistory = channel.unary_unary(
                '/qtown.Academy/SearchHistory',
                request_serializer=qtown_dot_academy__pb2.SearchHistoryRequest.SerializeToString,
                response_deserializer=qtown_dot_academy__pb2.SearchHistoryResponse.FromString,
                _registered_method=True)
        self.GetModelStats = channel.unary_unary(
                '/qtown.Academy/GetModelStats',
                request_serializer=qtown_dot_academy__pb2.ModelStatsRequest.SerializeToString,
                response_deserializer=qtown_dot_academy__pb2.ModelStatsResponse.FromString,
                _registered_method=True)
        self.NPCArrive = channel.unary_unary(
                '/qtown.Academy/NPCArrive',
                request_serializer=qtown_dot_common__pb2.TravelRequest.SerializeToString,
                response_deserializer=qtown_dot_common__pb2.TravelResponse.FromString,
                _registered_method=True)
        self.NPCDepart = channel.unary_unary(
                '/qtown.Academy/NPCDepart',
                request_serializer=qtown_dot_common__pb2.TravelRequest.SerializeToString,
                response_deserializer=qtown_dot_common__pb2.TravelResponse.FromString,
                _registered_method=True)


class AcademyServicer(object):
    """─── Academy Service (Python + LangChain/LangGraph + Ollama) ───
    AI/ML neighborhood. NPC decision agents, multi-model routing,
    RAG over town history via pgvector.
    Proves: LangGraph state machines, Ollama local inference, RAG source attribution.

    """

    def Health(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NPCDecide(self, request, context):
        """NPC decision — runs the LangGraph agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDialogue(self, request, context):
        """Content generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateNewspaper(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchHistory(self, request, context):
        """RAG — search town history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelStats(self, request, context):
        """Model routing stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NPCArrive(self, request, context):
        """NPC travel
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NPCDepart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcademyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=qtown_dot_common__pb2.HealthRequest.FromString,
                    response_serializer=qtown_dot_common__pb2.HealthResponse.SerializeToString,
            ),
            'NPCDecide': grpc.unary_unary_rpc_method_handler(
                    servicer.NPCDecide,
                    request_deserializer=qtown_dot_academy__pb2.NPCDecideRequest.FromString,
                    response_serializer=qtown_dot_academy__pb2.NPCDecideResponse.SerializeToString,
            ),
            'GenerateDialogue': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDialogue,
                    request_deserializer=qtown_dot_academy__pb2.DialogueRequest.FromString,
                    response_serializer=qtown_dot_academy__pb2.DialogueResponse.SerializeToString,
            ),
            'GenerateNewspaper': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateNewspaper,
                    request_deserializer=qtown_dot_academy__pb2.NewspaperRequest.FromString,
                    response_serializer=qtown_dot_academy__pb2.NewspaperResponse.SerializeToString,
            ),
            'SearchHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchHistory,
                    request_deserializer=qtown_dot_academy__pb2.SearchHistoryRequest.FromString,
                    response_serializer=qtown_dot_academy__pb2.SearchHistoryResponse.SerializeToString,
            ),
            'GetModelStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelStats,
                    request_deserializer=qtown_dot_academy__pb2.ModelStatsRequest.FromString,
                    response_serializer=qtown_dot_academy__pb2.ModelStatsResponse.SerializeToString,
            ),
            'NPCArrive': grpc.unary_unary_rpc_method_handler(
                    servicer.NPCArrive,
                    request_deserializer=qtown_dot_common__pb2.TravelRequest.FromString,
                    response_serializer=qtown_dot_common__pb2.TravelResponse.SerializeToString,
            ),
            'NPCDepart': grpc.unary_unary_rpc_method_handler(
                    servicer.NPCDepart,
                    request_deserializer=qtown_dot_common__pb2.TravelRequest.FromString,
                    response_serializer=qtown_dot_common__pb2.TravelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qtown.Academy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qtown.Academy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Academy(object):
    """─── Academy Service (Python + LangChain/LangGraph + Ollama) ───
    AI/ML neighborhood. NPC decision agents, multi-model routing,
    RAG over town history via pgvector.
    Proves: LangGraph state machines, Ollama local inference, RAG source attribution.

    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/Health',
            qtown_dot_common__pb2.HealthRequest.SerializeToString,
            qtown_dot_common__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NPCDecide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/NPCDecide',
            qtown_dot_academy__pb2.NPCDecideRequest.SerializeToString,
            qtown_dot_academy__pb2.NPCDecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDialogue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/GenerateDialogue',
            qtown_dot_academy__pb2.DialogueRequest.SerializeToString,
            qtown_dot_academy__pb2.DialogueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateNewspaper(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/GenerateNewspaper',
            qtown_dot_academy__pb2.NewspaperRequest.SerializeToString,
            qtown_dot_academy__pb2.NewspaperResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/SearchHistory',
            qtown_dot_academy__pb2.SearchHistoryRequest.SerializeToString,
            qtown_dot_academy__pb2.SearchHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/GetModelStats',
            qtown_dot_academy__pb2.ModelStatsRequest.SerializeToString,
            qtown_dot_academy__pb2.ModelStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NPCArrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/NPCArrive',
            qtown_dot_common__pb2.TravelRequest.SerializeToString,
            qtown_dot_common__pb2.TravelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NPCDepart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qtown.Academy/NPCDepart',
            qtown_dot_common__pb2.TravelRequest.SerializeToString,
            qtown_dot_common__pb2.TravelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
