package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net"
	"net/http"
	_ "net/http/pprof"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	marketgrpc "qtown/market-district/internal/grpc"
	"qtown/market-district/internal/kafka"
	pb "qtown/proto/qtown"
)

const (
	grpcPort = ":50051"
	httpPort = ":6060"
)

func main() {
	log.Println("[market-district] starting up")

	// --- gRPC server ---
	lis, err := net.Listen("tcp", grpcPort)
	if err != nil {
		log.Fatalf("[market-district] failed to listen on %s: %v", grpcPort, err)
	}

	grpcServer := grpc.NewServer()

	// --- Kafka producer (best-effort) ---
	// NewProducer only builds a writer; it doesn't dial, so a missing/unreachable
	// broker won't crash startup. Publish failures are logged and swallowed
	// inside MarketServer — a settled-trade event is never allowed to fail a trade.
	producer := kafka.NewProducer()
	defer producer.Close()

	marketSrv := marketgrpc.NewMarketServer(producer)

	// Register the gRPC service impl (generated by buf into gen/go). PlaceOrder,
	// GetOrderBook, PriceFeed, etc. are now reachable on :50051.
	pb.RegisterMarketDistrictServer(grpcServer, marketSrv)

	// Server reflection: lets grpcurl / ghz discover the service by name without
	// shipping .proto files to the client (used by the load test in docs/perf and
	// handy for manual probing). Harmless for a first-party dev service.
	reflection.Register(grpcServer)

	go func() {
		log.Printf("[market-district] gRPC server listening on %s", grpcPort)
		if err := grpcServer.Serve(lis); err != nil {
			log.Printf("[market-district] gRPC server stopped: %v", err)
		}
	}()

	// --- HTTP server (health + pprof) ---
	mux := http.NewServeMux()

	// pprof endpoints are registered on DefaultServeMux by the net/http/pprof import
	mux.Handle("/debug/pprof/", http.DefaultServeMux)

	mux.HandleFunc("/health", func(w http.ResponseWriter, r *http.Request) {
		resp, err := marketSrv.Health(r.Context(), &pb.HealthRequest{})
		w.Header().Set("Content-Type", "application/json")
		if err != nil {
			w.WriteHeader(http.StatusServiceUnavailable)
			if encErr := json.NewEncoder(w).Encode(map[string]string{
				"status":  "error",
				"service": "market-district",
			}); encErr != nil {
				log.Printf("[market-district] health encode error: %v", encErr)
			}
			return
		}
		w.WriteHeader(http.StatusOK)
		payload := map[string]interface{}{
			"status":  resp.Status,
			"service": resp.Service,
			"details": resp.Details,
		}
		if err := json.NewEncoder(w).Encode(payload); err != nil {
			log.Printf("[market-district] health encode error: %v", err)
		}
	})

	// --- Read-model (JSON over HTTP) ---
	// A lightweight, read-only view of the live book and recent trades for
	// dashboards/observability. Services still use gRPC; this exists so a
	// browser-facing BFF (the dashboard's Nitro layer) can render real Market
	// data over plain JSON without a gRPC client. An unknown resource returns an
	// empty book / empty trades (200), never a fabricated one.
	mux.HandleFunc("/api/orderbook", func(w http.ResponseWriter, r *http.Request) {
		resource := r.URL.Query().Get("resource")
		snap, err := marketSrv.GetOrderBook(r.Context(), &pb.OrderBookRequest{Resource: resource, Depth: 20})
		if err != nil {
			writeJSONError(w, err)
			return
		}
		writeJSON(w, orderBookView(resource, snap))
	})

	mux.HandleFunc("/api/trades", func(w http.ResponseWriter, r *http.Request) {
		resource := r.URL.Query().Get("resource")
		limit := parseLimit(r.URL.Query().Get("limit"), 50)
		resp, err := marketSrv.GetTrades(r.Context(), &pb.GetTradesRequest{Resource: resource, Limit: int32(limit)})
		if err != nil {
			writeJSONError(w, err)
			return
		}
		writeJSON(w, tradesView(resp))
	})

	httpServer := &http.Server{
		Addr:         httpPort,
		Handler:      mux,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
	}

	go func() {
		log.Printf("[market-district] HTTP server listening on %s", httpPort)
		if err := httpServer.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Printf("[market-district] HTTP server error: %v", err)
		}
	}()

	// --- Kafka consumer placeholder ---
	go runKafkaConsumer()

	// --- Graceful shutdown ---
	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	sig := <-quit
	log.Printf("[market-district] received signal %s, shutting down", sig)

	grpcServer.GracefulStop()
	log.Println("[market-district] gRPC server stopped")

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := httpServer.Shutdown(ctx); err != nil {
		log.Printf("[market-district] HTTP shutdown error: %v", err)
	}
	log.Println("[market-district] shutdown complete")
}

// runKafkaConsumer is a placeholder for the Kafka consumer loop.
// Replace with a real kafka-go reader once topics are defined.
func runKafkaConsumer() {
	brokers := os.Getenv("KAFKA_BROKERS")
	if brokers == "" {
		brokers = "localhost:9092"
	}
	topic := os.Getenv("KAFKA_TOPIC")
	if topic == "" {
		topic = "qtown.market.orders"
	}

	log.Printf("[market-district] kafka consumer placeholder — broker=%s topic=%s", brokers, topic)

	// Example usage once real consumer is wired in:
	//
	// r := kafka.NewReader(kafka.ReaderConfig{
	//     Brokers:  []string{brokers},
	//     Topic:    topic,
	//     GroupID:  "market-district-consumer",
	//     MinBytes: 1e3,
	//     MaxBytes: 10e6,
	// })
	// defer r.Close()
	// for {
	//     m, err := r.ReadMessage(context.Background())
	//     if err != nil { break }
	//     fmt.Printf("kafka message at offset %d: %s = %s\n", m.Offset, m.Key, m.Value)
	// }

	fmt.Println("[market-district] kafka consumer: not yet connected (placeholder)")
}

// --- read-model view types ---
// Deliberately small, stable DTOs mapped from the proto so the dashboard's JSON
// contract doesn't couple to generated protobuf internals.

type levelView struct {
	Price    float64 `json:"price"`
	Quantity float64 `json:"quantity"`
}

type bookView struct {
	Resource string      `json:"resource"`
	Bids     []levelView `json:"bids"`
	Asks     []levelView `json:"asks"`
	MidPrice float64     `json:"midPrice"`
	Spread   float64     `json:"spread"`
}

type tradeView struct {
	ID       string  `json:"id"`
	Resource string  `json:"resource"`
	Price    float64 `json:"price"`
	Quantity float64 `json:"quantity"`
	Ts       int64   `json:"ts"` // unix seconds
}

func orderBookView(resource string, snap *pb.OrderBookSnapshot) bookView {
	v := bookView{Resource: resource, Bids: []levelView{}, Asks: []levelView{}, MidPrice: float64(snap.MidPrice)}
	for _, b := range snap.Bids {
		v.Bids = append(v.Bids, levelView{Price: float64(b.Price), Quantity: float64(b.Quantity)})
	}
	for _, a := range snap.Asks {
		v.Asks = append(v.Asks, levelView{Price: float64(a.Price), Quantity: float64(a.Quantity)})
	}
	if len(snap.Bids) > 0 && len(snap.Asks) > 0 {
		v.Spread = float64(snap.Asks[0].Price - snap.Bids[0].Price)
	}
	return v
}

func tradesView(resp *pb.GetTradesResponse) []tradeView {
	out := make([]tradeView, 0, len(resp.Trades))
	for _, t := range resp.Trades {
		var ts int64
		if t.Timestamp != nil {
			ts = t.Timestamp.Seconds
		}
		out = append(out, tradeView{
			ID:       t.Id,
			Resource: t.Resource,
			Price:    float64(t.Price),
			Quantity: float64(t.Quantity),
			Ts:       ts,
		})
	}
	return out
}

func writeJSON(w http.ResponseWriter, v interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)
	if err := json.NewEncoder(w).Encode(v); err != nil {
		log.Printf("[market-district] read-model encode error: %v", err)
	}
}

func writeJSONError(w http.ResponseWriter, err error) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusServiceUnavailable)
	if encErr := json.NewEncoder(w).Encode(map[string]string{"error": err.Error()}); encErr != nil {
		log.Printf("[market-district] read-model error encode failed: %v", encErr)
	}
}

func parseLimit(s string, def int) int {
	if s == "" {
		return def
	}
	n, err := strconv.Atoi(s)
	if err != nil || n <= 0 {
		return def
	}
	if n > 200 {
		return 200
	}
	return n
}
