//! Audit log — persists all validation results to Postgres.
//!
//! Validation results are buffered in memory and flushed in bulk to the
//! `fortress.validation_log` table in the shared Postgres instance. This
//! keeps the hot validation path free of synchronous I/O: the buffer is
//! flushed when it reaches `flush_at` entries or when `AuditLog` is dropped.
//!
//! # Table contract (DDL not managed here)
//!
//! ```sql
//! CREATE TABLE IF NOT EXISTS fortress.validation_log (
//!     id          BIGSERIAL PRIMARY KEY,
//!     event_id    TEXT        NOT NULL,
//!     rule_name   TEXT        NOT NULL,
//!     valid       BOOLEAN     NOT NULL,
//!     message     TEXT,
//!     logged_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
//! );
//! ```
//!
//! # Postgres integration
//!
//! The actual INSERT is currently a placeholder. Phase 3 will replace the
//! `flush` body with a `tokio-postgres` or `sqlx` batch insert using the
//! connection string from `DATABASE_URL`.

use std::env;

use tracing::{info, warn};

// ─────────────────────────────────────────────────────────────────────────────

/// A single validation result to be persisted to the audit log.
#[derive(Debug, Clone)]
pub struct AuditEntry {
    /// Unique identifier for the originating event.
    ///
    /// For Kafka-sourced events this is `"{npc_id}:{event_type}:{offset}"`;
    /// for gRPC-sourced events it is a UUID generated by the caller.
    pub event_id: String,

    /// Machine-readable rule name (matches `Rule::name()` exactly).
    pub rule_name: String,

    /// `true` if the event passed this rule.
    pub valid: bool,

    /// Human-readable explanation; `None` for passing results.
    pub message: Option<String>,
}

// ─────────────────────────────────────────────────────────────────────────────

/// Buffers `AuditEntry` values and flushes them in bulk to Postgres.
///
/// # Thread safety
///
/// `AuditLog` is **not** `Send + Sync` on its own — callers that need to share
/// it across async tasks should wrap it in a `tokio::sync::Mutex`. The design
/// intentionally keeps locking out of the core type to give callers control
/// over contention strategy.
pub struct AuditLog {
    /// Postgres connection string read from the environment.
    database_url: String,

    /// In-memory buffer of entries pending insertion.
    buffer: Vec<AuditEntry>,

    /// Flush the buffer to Postgres when this many entries are queued.
    flush_at: usize,
}

impl AuditLog {
    /// Creates a new `AuditLog` with a 500-entry flush threshold.
    ///
    /// The `DATABASE_URL` environment variable is read at construction time;
    /// if absent the default development DSN is used.
    pub fn new() -> Self {
        let database_url = env::var("DATABASE_URL").unwrap_or_else(|_| {
            "postgresql://qtown:qtown_dev@localhost:5432/qtown".to_string()
        });

        Self {
            database_url,
            buffer: Vec::with_capacity(1_000),
            flush_at: 500,
        }
    }

    /// Creates a new `AuditLog` with a custom flush threshold.
    ///
    /// Useful in tests to force immediate flushing (`flush_at = 1`) or to
    /// tune memory usage in high-throughput deployments.
    pub fn with_flush_threshold(flush_at: usize) -> Self {
        let mut log = Self::new();
        log.flush_at = flush_at;
        log
    }

    /// Returns the number of entries currently buffered (not yet flushed).
    pub fn buffered(&self) -> usize {
        self.buffer.len()
    }

    /// Appends an entry to the buffer.
    ///
    /// If the buffer reaches `flush_at` entries, `flush` is called
    /// automatically to prevent unbounded memory growth.
    pub fn log(&mut self, entry: AuditEntry) {
        self.buffer.push(entry);
        if self.buffer.len() >= self.flush_at {
            self.flush();
        }
    }

    /// Flushes all buffered entries to Postgres and clears the buffer.
    ///
    /// # Current behaviour (placeholder)
    ///
    /// Logs the flush at `info` level. Phase 3 will replace this with a real
    /// batch INSERT via `tokio-postgres` or `sqlx`:
    ///
    /// ```sql
    /// INSERT INTO fortress.validation_log (event_id, rule_name, valid, message)
    /// VALUES ($1, $2, $3, $4), ($5, $6, $7, $8), ...
    /// ```
    ///
    /// # Error handling
    ///
    /// Database errors in the real implementation should be logged and the
    /// buffer re-queued (or dead-lettered) rather than silently dropped.
    pub fn flush(&mut self) {
        if self.buffer.is_empty() {
            return;
        }

        let count = self.buffer.len();

        // TODO Phase 3: replace with actual tokio-postgres / sqlx batch insert.
        //
        // Example (sqlx):
        //
        //   let mut query_builder = QueryBuilder::new(
        //       "INSERT INTO fortress.validation_log (event_id, rule_name, valid, message) "
        //   );
        //   query_builder.push_values(self.buffer.drain(..), |mut b, entry| {
        //       b.push_bind(entry.event_id)
        //        .push_bind(entry.rule_name)
        //        .push_bind(entry.valid)
        //        .push_bind(entry.message);
        //   });
        //   query_builder.build().execute(&pool).await?;

        info!(
            count,
            db = %self.database_url,
            "audit_log: flushing entries to fortress.validation_log (placeholder)"
        );

        if count > 0 {
            let invalid_count = self.buffer.iter().filter(|e| !e.valid).count();
            if invalid_count > 0 {
                warn!(
                    invalid_count,
                    "audit_log: {} of {} flushed entries were invalid",
                    invalid_count,
                    count
                );
            }
        }

        self.buffer.clear();
    }
}

impl Default for AuditLog {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for AuditLog {
    /// Flushes any remaining buffered entries when the log is dropped.
    ///
    /// This ensures no entries are silently discarded during graceful shutdown.
    fn drop(&mut self) {
        if !self.buffer.is_empty() {
            info!(
                remaining = self.buffer.len(),
                "audit_log: flushing remaining entries on drop"
            );
            self.flush();
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(valid: bool) -> AuditEntry {
        AuditEntry {
            event_id: "evt_001".to_string(),
            rule_name: "GoldSufficientRule".to_string(),
            valid,
            message: if valid {
                None
            } else {
                Some("insufficient gold".to_string())
            },
        }
    }

    #[test]
    fn buffer_grows_until_flush_threshold() {
        let mut log = AuditLog::with_flush_threshold(3);
        log.log(entry(true));
        assert_eq!(log.buffered(), 1);
        log.log(entry(true));
        assert_eq!(log.buffered(), 2);
        // Third entry triggers auto-flush.
        log.log(entry(false));
        assert_eq!(log.buffered(), 0, "buffer should be cleared after auto-flush");
    }

    #[test]
    fn manual_flush_clears_buffer() {
        let mut log = AuditLog::with_flush_threshold(100);
        for _ in 0..10 {
            log.log(entry(true));
        }
        assert_eq!(log.buffered(), 10);
        log.flush();
        assert_eq!(log.buffered(), 0);
    }

    #[test]
    fn flush_on_empty_buffer_is_noop() {
        let mut log = AuditLog::new();
        log.flush(); // should not panic
        assert_eq!(log.buffered(), 0);
    }

    #[test]
    fn drop_flushes_remaining_entries() {
        // Wrap in a block to trigger Drop before assertions.
        let populated = {
            let mut log = AuditLog::with_flush_threshold(1_000);
            for _ in 0..5 {
                log.log(entry(true));
            }
            log.buffered()
        };
        // The value captured before drop should have been 5.
        assert_eq!(populated, 5);
        // After drop, the log is gone — we just verify it didn't panic.
    }
}
